#!/bin/bash
# Skip the config file name argument.

declare csv=$2

echo "
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-little-dns
data:
  name: "$0"
  elementname: "$1"
  csventry: "$csv"
  content: |-
    "`cat $csv`"
"
